"""Source-blind example tests for issue #34:
feat: optional Ollama advisor — rank + explain only, offline-graceful

Every test is derived from the acceptance criteria text only (Red phase TDD).
No implementation source was read during authoring.

Design choices (from criteria text, not from source):
  - Module path: sentinel.advisor.ollama exports OllamaAdvisor, NullAdvisor, build_advisor
  - Injection: build_advisor(config, *, _url_opener=None) — follows the build_wake_proxy pattern
  - detection.candidates is a tuple[str, ...] of target names (containers / app names)
  - OllamaAdvisor posts to {base_url}/api/chat (or /api/generate) with a JSON body
    that contains at minimum "model" and "keep_alive": 0
  - The model response body is parsed to extract a JSON object with keys:
      "ranking"      — ordered list of target names (defines ordered_targets)
      "explanations" — dict mapping each target name to a human-readable string
    For the /api/chat endpoint the JSON lives in message.content;
    for /api/generate it lives in the response field.
  - Fake response uses the /api/chat envelope; the /api/generate envelope is
    tested by a separate helper (both must be acceptable per the criterion).
  - Identity ranking: ordered_targets == detection.candidates (input order),
    explanations == {} (empty dict)
  - AdvisorConfig new fields required by this issue:
      base_url: str  (default "http://localhost:11434")
      model: str     (default "glm-5.2:cloud")
      request_timeout: float
  - All network calls are intercepted via the injected _url_opener callable;
    no real network traffic is generated by any test.

Skipped criteria (oracle: NOT VERIFIABLE):
  - "The advisor never adds, removes, or vetoes a candidate — only reorders"
    (oracle: no concrete runtime or unit check inferable — skip)
  - SOLID, clean code (subjective prose, no unit assertion — skip)
"""

from __future__ import annotations

import dataclasses
import json
import socket
import urllib.error
import urllib.request

from hypothesis import given, settings, strategies as st

from sentinel.config import AdvisorConfig
from sentinel.domain.value_objects import AdvisorRanking
from sentinel.advisor.ollama import NullAdvisor, build_advisor


# ── Fake detection type ────────────────────────────────────────────────────────


@dataclasses.dataclass(frozen=True)
class _FakeDetection:
    """Minimal detection stand-in.

    Assumption: the real detection type exposes .candidates — a sequence of
    target name strings that the advisor should rank.
    """

    candidates: tuple[str, ...]


# ── Fake HTTP infrastructure ───────────────────────────────────────────────────


class _FakeHTTPResponse:
    """Minimal urllib-response stand-in (supports the context-manager protocol)."""

    def __init__(self, status: int, body: bytes) -> None:
        self.status = status
        self._body = body

    def read(self) -> bytes:
        return self._body

    def __enter__(self) -> "_FakeHTTPResponse":
        return self

    def __exit__(self, *_args: object) -> None:
        pass


class _CapturingUrlOpener:
    """Drop-in for urllib.request.urlopen that captures every call."""

    def __init__(
        self,
        response: _FakeHTTPResponse | None = None,
        side_effect: Exception | None = None,
    ) -> None:
        self.calls: list[dict] = []
        self._response = response
        self._side_effect = side_effect

    def __call__(
        self, request: object, timeout: float | None = None
    ) -> _FakeHTTPResponse:
        call_record: dict = {"timeout": timeout}
        if isinstance(request, urllib.request.Request):
            call_record["url"] = request.full_url
            call_record["data"] = request.data
            call_record["method"] = request.get_method()
        else:
            call_record["url"] = str(request)
            call_record["data"] = None
            call_record["method"] = None
        self.calls.append(call_record)

        if self._side_effect is not None:
            raise self._side_effect
        assert self._response is not None
        return self._response


# ── Response body builders ─────────────────────────────────────────────────────


def _chat_response_body(candidates: tuple[str, ...]) -> bytes:
    """Build a realistic /api/chat response.

    The model ranks candidates in REVERSED order so the test can verify the
    advisor actually parsed the response rather than returning the input order.
    """
    ranked = list(reversed(candidates))
    explanations = {
        name: f"ranked #{i + 1} by advisor" for i, name in enumerate(ranked)
    }
    content = json.dumps({"ranking": ranked, "explanations": explanations})
    envelope = {
        "model": "glm-5.2:cloud",
        "message": {"role": "assistant", "content": content},
        "done": True,
    }
    return json.dumps(envelope).encode()


def _generate_response_body(candidates: tuple[str, ...]) -> bytes:
    """Build a realistic /api/generate response (alternative endpoint per criterion)."""
    ranked = list(reversed(candidates))
    explanations = {
        name: f"ranked #{i + 1} by advisor" for i, name in enumerate(ranked)
    }
    payload = json.dumps({"ranking": ranked, "explanations": explanations})
    envelope = {
        "model": "glm-5.2:cloud",
        "response": payload,
        "done": True,
    }
    return json.dumps(envelope).encode()


# ── Test helpers ───────────────────────────────────────────────────────────────


def _make_config(
    *,
    enabled: bool = True,
    base_url: str = "http://localhost:11434",
    model: str = "glm-5.2:cloud",
    request_timeout: float = 5.0,
) -> AdvisorConfig:
    return AdvisorConfig(
        enabled=enabled,
        base_url=base_url,
        model=model,
        request_timeout=request_timeout,
    )


def _make_advisor(
    *,
    enabled: bool = True,
    base_url: str = "http://localhost:11434",
    model: str = "glm-5.2:cloud",
    request_timeout: float = 5.0,
    url_opener: object | None = None,
) -> object:
    config = _make_config(
        enabled=enabled,
        base_url=base_url,
        model=model,
        request_timeout=request_timeout,
    )
    return build_advisor(config, _url_opener=url_opener)


def _detection(*names: str) -> _FakeDetection:
    return _FakeDetection(candidates=names)


# ===========================================================================
# AdvisorConfig: new fields required by this issue
# ===========================================================================


class TestAdvisorConfigNewFields:
    def test_when_base_url_not_given_then_default_contains_localhost_11434(self):
        cfg = AdvisorConfig()
        assert "localhost:11434" in cfg.base_url, (
            f"Default base_url must target localhost:11434; got {cfg.base_url!r}"
        )

    def test_when_model_not_given_then_default_is_glm_family(self):
        cfg = AdvisorConfig()
        assert cfg.model, "AdvisorConfig must expose a non-empty default model name"

    def test_when_request_timeout_not_given_then_default_is_positive(self):
        cfg = AdvisorConfig()
        assert cfg.request_timeout > 0, (
            f"Default request_timeout must be positive; got {cfg.request_timeout!r}"
        )

    def test_when_request_timeout_is_given_then_value_is_preserved(self):
        cfg = AdvisorConfig(request_timeout=42.0)
        assert cfg.request_timeout == 42.0

    def test_when_model_is_given_then_value_is_preserved(self):
        cfg = AdvisorConfig(model="llama3:latest")
        assert cfg.model == "llama3:latest"

    def test_when_base_url_is_given_then_value_is_preserved(self):
        cfg = AdvisorConfig(base_url="http://localhost:11434")
        assert cfg.base_url == "http://localhost:11434"


# ===========================================================================
# AC1 (T2) — OllamaAdvisor.rank(detection) → AdvisorRanking
#             POSTs to {base_url}/api/chat (or /api/generate) with model +
#             keep_alive=0, parses JSON ordering, returns ordered targets +
#             per-target explanations
# ===========================================================================


def test_when_rank_is_called_then_exactly_one_http_call_is_made():
    """rank() must issue exactly one outbound HTTP call per invocation."""
    det = _detection("A", "B")
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(det.candidates))
    )
    advisor = _make_advisor(url_opener=opener)

    advisor.rank(det)

    assert len(opener.calls) == 1, (
        f"Expected exactly 1 HTTP call; got {len(opener.calls)}"
    )


def test_when_rank_is_called_then_url_targets_configured_base_url():
    """The HTTP call must go to {base_url}/api/chat or {base_url}/api/generate."""
    det = _detection("A", "B")
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(det.candidates))
    )
    advisor = _make_advisor(base_url="http://localhost:11434", url_opener=opener)

    advisor.rank(det)

    url = opener.calls[0]["url"]
    assert "localhost:11434" in url, (
        f"Expected localhost:11434 in request URL; got {url!r}"
    )
    assert "/api/chat" in url or "/api/generate" in url, (
        f"Expected /api/chat or /api/generate in URL; got {url!r}"
    )


def test_when_rank_is_called_then_request_body_contains_configured_model():
    """Request body must carry the configured model name."""
    det = _detection("A", "B")
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(det.candidates))
    )
    advisor = _make_advisor(model="glm-5.2:cloud", url_opener=opener)

    advisor.rank(det)

    raw = opener.calls[0]["data"]
    assert raw is not None, "Request must have a body"
    body = json.loads(raw)
    assert body.get("model") == "glm-5.2:cloud", (
        f"Expected model='glm-5.2:cloud' in request body; got {body.get('model')!r}"
    )


def test_when_rank_is_called_then_request_body_contains_keep_alive_zero():
    """Request body must include keep_alive=0 so the runner unloads immediately."""
    det = _detection("A", "B")
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(det.candidates))
    )
    advisor = _make_advisor(url_opener=opener)

    advisor.rank(det)

    raw = opener.calls[0]["data"]
    body = json.loads(raw)
    assert body.get("keep_alive") == 0, (
        f"Expected keep_alive=0 in request body; got {body.get('keep_alive')!r}"
    )


def test_when_rank_is_called_with_valid_chat_response_then_advisor_ranking_is_returned():
    """rank() must return an AdvisorRanking on a successful /api/chat response."""
    det = _detection("clipcraft_api", "clipcraft_frontend")
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(det.candidates))
    )
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    assert isinstance(result, AdvisorRanking), (
        f"Expected AdvisorRanking; got {type(result).__name__}"
    )


def test_when_rank_is_called_with_valid_response_then_ordered_targets_match_model_ranking():
    """ordered_targets must reflect the ranking embedded in the response, not the input order.

    The fake response ranks candidates in REVERSED order; the advisor must honour that.
    """
    candidates = ("alpha", "beta", "gamma")
    det = _FakeDetection(candidates=candidates)
    expected_order = tuple(reversed(candidates))  # what the fake response specifies

    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(candidates))
    )
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    assert result.ordered_targets == expected_order, (
        f"ordered_targets must follow the model ranking {expected_order!r}; "
        f"got {result.ordered_targets!r}"
    )


def test_when_rank_is_called_with_valid_response_then_explanations_are_non_empty_strings():
    """Each ranked target must have a non-empty explanation string."""
    candidates = ("clipcraft_api", "clipcraft_frontend")
    det = _FakeDetection(candidates=candidates)
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(candidates))
    )
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    for target in result.ordered_targets:
        assert target in result.explanations, (
            f"explanation missing for target {target!r}"
        )
        assert (
            isinstance(result.explanations[target], str) and result.explanations[target]
        ), (
            f"explanation for {target!r} must be a non-empty string; "
            f"got {result.explanations[target]!r}"
        )


def test_when_rank_is_called_with_valid_generate_response_then_advisor_ranking_is_returned():
    """Alternatively: rank() also accepts and parses /api/generate response envelopes."""
    candidates = ("svc_a", "svc_b")
    det = _FakeDetection(candidates=candidates)
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _generate_response_body(candidates))
    )
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    assert isinstance(result, AdvisorRanking)
    assert set(result.ordered_targets) == set(candidates), (
        f"ordered_targets must be a permutation of input candidates; "
        f"got {result.ordered_targets!r}"
    )


# ===========================================================================
# AC2 (UNIT) — Any failure returns identity ranking; rank() never raises
# ===========================================================================


def test_when_connection_is_refused_then_identity_ranking_is_returned():
    """ConnectionRefusedError → candidates in input order, empty explanations."""
    det = _detection("A", "B", "C")
    opener = _CapturingUrlOpener(
        side_effect=urllib.error.URLError(ConnectionRefusedError())
    )
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    assert isinstance(result, AdvisorRanking)
    assert result.ordered_targets == det.candidates, (
        f"Identity ranking expected {det.candidates!r}; got {result.ordered_targets!r}"
    )
    assert result.explanations == {}, (
        f"Explanations must be empty on failure; got {result.explanations!r}"
    )


def test_when_connection_is_refused_then_no_exception_is_raised():
    """rank() must swallow ConnectionRefusedError and never propagate it."""
    det = _detection("A", "B")
    opener = _CapturingUrlOpener(
        side_effect=urllib.error.URLError(ConnectionRefusedError())
    )
    advisor = _make_advisor(url_opener=opener)
    advisor.rank(det)  # must not raise


def test_when_request_times_out_then_identity_ranking_is_returned():
    """socket.timeout → identity ranking (input order, empty explanations)."""
    det = _detection("X", "Y")
    opener = _CapturingUrlOpener(side_effect=urllib.error.URLError(socket.timeout()))
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    assert result.ordered_targets == det.candidates
    assert result.explanations == {}


def test_when_request_times_out_then_no_exception_is_raised():
    """rank() must swallow socket.timeout and never propagate it."""
    det = _detection("X", "Y")
    opener = _CapturingUrlOpener(side_effect=urllib.error.URLError(socket.timeout()))
    advisor = _make_advisor(url_opener=opener)
    advisor.rank(det)  # must not raise


def test_when_response_status_is_not_200_then_identity_ranking_is_returned():
    """HTTP 503 Service Unavailable → identity ranking."""
    det = _detection("P", "Q")
    http_error = urllib.error.HTTPError(
        url="http://localhost:11434/api/chat",
        code=503,
        msg="Service Unavailable",
        hdrs=None,  # type: ignore[arg-type]
        fp=None,
    )
    opener = _CapturingUrlOpener(side_effect=http_error)
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    assert result.ordered_targets == det.candidates
    assert result.explanations == {}


def test_when_response_status_is_not_200_then_no_exception_is_raised():
    """rank() must swallow HTTPError for non-2xx status and never propagate it."""
    det = _detection("P", "Q")
    http_error = urllib.error.HTTPError(
        url="http://localhost:11434/api/chat",
        code=500,
        msg="Internal Server Error",
        hdrs=None,  # type: ignore[arg-type]
        fp=None,
    )
    opener = _CapturingUrlOpener(side_effect=http_error)
    advisor = _make_advisor(url_opener=opener)
    advisor.rank(det)  # must not raise


def test_when_response_body_is_not_valid_json_then_identity_ranking_is_returned():
    """Malformed (non-JSON) response body → identity ranking (never raises)."""
    det = _detection("R", "S")
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, b"this is not json at all!!!")
    )
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    assert result.ordered_targets == det.candidates
    assert result.explanations == {}


def test_when_response_body_is_not_valid_json_then_no_exception_is_raised():
    """rank() must swallow JSON parse errors and never propagate them."""
    det = _detection("R", "S")
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, b"<html>not json</html>")
    )
    advisor = _make_advisor(url_opener=opener)
    advisor.rank(det)  # must not raise


def test_when_response_body_is_empty_then_identity_ranking_is_returned():
    """Empty response body → identity ranking (never raises)."""
    det = _detection("M", "N")
    opener = _CapturingUrlOpener(response=_FakeHTTPResponse(200, b""))
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    assert result.ordered_targets == det.candidates
    assert result.explanations == {}


def test_when_response_body_is_json_but_ranking_key_is_missing_then_identity_ranking_is_returned():
    """Well-formed JSON with no 'ranking' key → identity ranking."""
    det = _detection("M", "N")
    body = json.dumps({"unexpected_key": "value"}).encode()
    opener = _CapturingUrlOpener(response=_FakeHTTPResponse(200, body))
    advisor = _make_advisor(url_opener=opener)

    result = advisor.rank(det)

    assert result.ordered_targets == det.candidates
    assert result.explanations == {}


# ===========================================================================
# AC3 (UNIT) — build_advisor(config) returns NullAdvisor when enabled=False;
#              no network call; identity passthrough
# ===========================================================================


def test_when_enabled_is_false_then_build_advisor_returns_null_advisor():
    """build_advisor(AdvisorConfig(enabled=False)) must return a NullAdvisor."""
    config = AdvisorConfig(enabled=False)

    result = build_advisor(config)

    assert isinstance(result, NullAdvisor), (
        f"Expected NullAdvisor when enabled=False; got {type(result).__name__}"
    )


def test_when_enabled_is_false_then_null_advisor_returns_candidates_in_input_order():
    """NullAdvisor.rank() must return ordered_targets == detection.candidates (identity)."""
    config = AdvisorConfig(enabled=False)
    advisor = build_advisor(config)
    det = _detection("alpha", "beta", "gamma")

    result = advisor.rank(det)

    assert isinstance(result, AdvisorRanking)
    assert result.ordered_targets == det.candidates, (
        f"NullAdvisor must preserve input order; "
        f"expected {det.candidates!r}, got {result.ordered_targets!r}"
    )


def test_when_enabled_is_false_then_null_advisor_returns_empty_explanations():
    """NullAdvisor.rank() must return an empty explanations dict."""
    config = AdvisorConfig(enabled=False)
    advisor = build_advisor(config)
    det = _detection("alpha", "beta")

    result = advisor.rank(det)

    assert result.explanations == {}, (
        f"NullAdvisor must return empty explanations; got {result.explanations!r}"
    )


def test_when_enabled_is_false_then_no_network_call_is_made():
    """NullAdvisor must not invoke the URL opener — no egress whatsoever."""
    call_count = 0

    def _spy_opener(request: object, timeout: float | None = None) -> object:
        nonlocal call_count
        call_count += 1
        raise AssertionError("NullAdvisor must not make any network call")

    config = AdvisorConfig(enabled=False)
    advisor = build_advisor(config, _url_opener=_spy_opener)
    det = _detection("alpha")

    advisor.rank(det)

    assert call_count == 0, (
        f"Expected 0 network calls from NullAdvisor; got {call_count}"
    )


def test_when_enabled_is_false_then_build_advisor_does_not_require_url_opener():
    """build_advisor(disabled config) must work without providing _url_opener."""
    config = AdvisorConfig(enabled=False)
    # Must not raise even when _url_opener is omitted entirely
    advisor = build_advisor(config)
    assert advisor is not None


# ===========================================================================
# AC4 (UNIT) — Request honours AdvisorConfig.request_timeout;
#              only egress is localhost:11434
# ===========================================================================


def test_when_rank_is_called_then_request_timeout_equals_advisor_config_value():
    """The configured request_timeout must be forwarded verbatim to the URL opener."""
    det = _detection("A", "B")
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(det.candidates))
    )
    expected_timeout = 7.5
    advisor = _make_advisor(request_timeout=expected_timeout, url_opener=opener)

    advisor.rank(det)

    actual_timeout = opener.calls[0]["timeout"]
    assert actual_timeout == expected_timeout, (
        f"Expected timeout={expected_timeout}; got {actual_timeout!r}"
    )


def test_when_advisor_is_built_with_default_config_then_base_url_is_localhost_11434():
    """Default AdvisorConfig.base_url must point to localhost:11434."""
    cfg = AdvisorConfig(enabled=True)
    assert "localhost:11434" in cfg.base_url, (
        f"Default base_url must contain localhost:11434; got {cfg.base_url!r}"
    )


def test_when_rank_is_called_then_request_url_does_not_contain_external_host():
    """The URL opener must never be called with a URL outside localhost."""
    det = _detection("A", "B")
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(det.candidates))
    )
    advisor = _make_advisor(base_url="http://localhost:11434", url_opener=opener)

    advisor.rank(det)

    url = opener.calls[0]["url"]
    assert "localhost" in url or "127.0.0.1" in url, (
        f"Egress URL must be localhost; got {url!r}"
    )


def test_when_different_timeout_values_are_configured_then_each_is_honoured():
    """Two advisors with different timeouts must each forward their own timeout."""
    det = _detection("X")

    for timeout_value in (1.0, 30.0, 60.0):
        opener = _CapturingUrlOpener(
            response=_FakeHTTPResponse(200, _chat_response_body(det.candidates))
        )
        advisor = _make_advisor(request_timeout=timeout_value, url_opener=opener)
        advisor.rank(det)

        assert opener.calls[0]["timeout"] == timeout_value, (
            f"Expected timeout={timeout_value}; got {opener.calls[0]['timeout']!r}"
        )


# ===========================================================================
# Property-based tests (Hypothesis) — invariants derived from criteria
# ===========================================================================


@given(
    st.lists(
        st.text(
            min_size=1,
            max_size=30,
            alphabet=st.characters(whitelist_categories=("L", "N", "P")),
        ),
        min_size=1,
        max_size=10,
        unique=True,
    )
)
@settings(max_examples=30, deadline=2000)
def test_when_any_network_failure_occurs_then_identity_ranking_is_always_returned(
    candidates: list[str],
) -> None:
    """Never-raises + identity invariant (AC2):
    for ANY non-empty candidate list, a network failure always returns exactly
    the input candidates in input order with empty explanations.
    """
    det = _FakeDetection(candidates=tuple(candidates))
    opener = _CapturingUrlOpener(
        side_effect=urllib.error.URLError(ConnectionRefusedError())
    )
    config = AdvisorConfig(
        enabled=True,
        base_url="http://localhost:11434",
        request_timeout=1.0,
    )
    advisor = build_advisor(config, _url_opener=opener)

    result = advisor.rank(det)

    assert isinstance(result, AdvisorRanking)
    assert result.ordered_targets == tuple(candidates), (
        f"Identity ranking must preserve input order on failure; "
        f"expected {tuple(candidates)!r}, got {result.ordered_targets!r}"
    )
    assert result.explanations == {}


@given(
    st.lists(
        st.text(
            min_size=1,
            max_size=30,
            alphabet=st.characters(whitelist_categories=("L", "N", "P")),
        ),
        min_size=0,
        max_size=10,
        unique=True,
    )
)
@settings(max_examples=30, deadline=2000)
def test_when_null_advisor_ranks_any_candidates_then_input_order_is_always_preserved(
    candidates: list[str],
) -> None:
    """Idempotence/identity invariant (AC3):
    NullAdvisor.rank() must always return candidates in the exact input order
    and with empty explanations, for any candidate list (including empty).
    """
    det = _FakeDetection(candidates=tuple(candidates))
    config = AdvisorConfig(enabled=False)
    advisor = build_advisor(config)

    result = advisor.rank(det)

    assert isinstance(result, AdvisorRanking)
    assert result.ordered_targets == tuple(candidates), (
        f"NullAdvisor must be identity; "
        f"expected {tuple(candidates)!r}, got {result.ordered_targets!r}"
    )
    assert result.explanations == {}


@given(
    st.floats(
        min_value=0.1,
        max_value=300.0,
        allow_nan=False,
        allow_infinity=False,
    )
)
@settings(max_examples=20, deadline=2000)
def test_when_any_positive_timeout_is_configured_then_it_is_forwarded_verbatim(
    timeout: float,
) -> None:
    """Never-raises + forwarding invariant (AC4):
    for any positive timeout value, rank() must pass it verbatim to the URL opener.
    """
    det = _FakeDetection(candidates=("a", "b"))
    opener = _CapturingUrlOpener(
        response=_FakeHTTPResponse(200, _chat_response_body(det.candidates))
    )
    config = AdvisorConfig(
        enabled=True,
        base_url="http://localhost:11434",
        request_timeout=timeout,
    )
    advisor = build_advisor(config, _url_opener=opener)

    advisor.rank(det)

    assert opener.calls
    assert opener.calls[0]["timeout"] == timeout, (
        f"timeout={timeout} must be forwarded verbatim; got {opener.calls[0]['timeout']!r}"
    )


@given(
    st.lists(
        st.text(
            min_size=1,
            max_size=30,
            alphabet=st.characters(whitelist_categories=("L", "N", "P")),
        ),
        min_size=1,
        max_size=8,
        unique=True,
    )
)
@settings(max_examples=20, deadline=2000)
def test_when_malformed_response_body_received_then_identity_ranking_always_returned(
    candidates: list[str],
) -> None:
    """Never-raises + identity invariant for malformed body (AC2):
    for any candidate list, a non-JSON response always yields identity ranking.
    """
    det = _FakeDetection(candidates=tuple(candidates))
    opener = _CapturingUrlOpener(response=_FakeHTTPResponse(200, b"not-json-{}[]"))
    config = AdvisorConfig(
        enabled=True,
        base_url="http://localhost:11434",
        request_timeout=1.0,
    )
    advisor = build_advisor(config, _url_opener=opener)

    result = advisor.rank(det)

    assert isinstance(result, AdvisorRanking)
    assert result.ordered_targets == tuple(candidates)
    assert result.explanations == {}
